### ISSUE TITLE
Same descriptions on two posts

### ISSUE THREAD

**Issue by nazmifeeroz** [phc5/my-blog#1]
Hi Paul!

I was passing by and read your blog... Great posts! I will use some for my interview candidates!

In [posts list](https://www.paulhyunchong.com/posts), I notice that *Learnings From User-Centric Performance* and *Creating my website* posts has the same description! 😅 

Have a good weekend!

**Comment by phc5** [comment]
Hey Nazmi!

Thanks for catching that :) I just pushed a fix with this commit: https://github.com/phc5/my-blog/commit/90bce87a8ba9b8e3e84cd4412e027c51ae56af38.
